baseURL = "https://samfeldstein.com/"
languageCode = "en-us"
title = "Sam Feldstein"
theme = "mainroad"

[Params]
description = "Sam Feldstein's personal website. Sam writes fantasy, horror, and science fiction stories."
post_meta = ["date", "categories"]
customCSS = ["css/custom.css"]
pager = true

[Params.style.vars]
fontFamilyPrimary = "'Courier New', 'serif'"
fontFamilySecondary = "'Fira Code', 'monospace'"

[Params.logo]
  # image = "img/placeholder.png" # Logo image. Path relative to "static"
  # title = "Practical Agonies" # Logo title, otherwise will use site title
  subtitle = "The teeth? We don't know. Signs from HaShem? Don't know. Helping others? Couldn't hurt."

[Params.sidebar]
  home = "right"
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["social", "recent", "categories", "taglist"]
  
  [Params.widgets.social]
  cached = true
  rss = "/index.xml"
  newsletter = "samfeldstein"
  instagram = "seldstein"

  [[Params.widgets.social.custom]]
  title = "Notebook"
  url = "https://publish.obsidian.md/sam-feldstein/homepage"

  [Params.widgets.search]
  cached = true

[Params.widgets.recent]
  cached = true

[Params.widgets.taglist]
  cached = true

[Params.widgets.categories]
  cached = true
